theme: jekyll-theme-cayman
title: The Franka Language
description: Franka is a simple and powerful open-source programming language not for programmers only.
show_downloads: false
google_analytics: UA-117837234-1